### ISSUE TITLE
Ubuntu LTS version packages

### ISSUE THREAD

**Issue by kokosowy** [HessiJames/soundkonverter#38]
Hi,

LTS versions of Ubuntu are wide used by people over the world and other distribution as well. I'd say packages for current and future LTS versions should be maintained to give people access to latest stable version of SoundKonverter.

As per [guide](https://github.com/HessiJames/soundkonverter/wiki/Installing%20soundKonverter#precompiled-packages) we still can get only 12.04 packages. I'd propose to maintain at least packages for latest LTS version of Ubuntu.

Other thing is 12.04 package is not containing latest release of SoundKonverter.

Why this is not bundled with KDE? This is the best ripper ever!

Thank you again,
K

**Comment by HessiJames** [comment]
Thank you, but I don't think the interest in soundkonverter was ever that big.

I use the open build service to build soundkonverter packages for various platforms. It's maintained by the opensuse folks and I guess canaonial isn't that interested in it. Newer versions of ubuntu don't include kcddb if I remember correctly, that's why I can't build packages for them.
And version 2.2 of soundkonverter won't build on ubuntu 12.04 because I'm using a "new" c++ feature.

**Comment by kokosowy** [comment]
You may be right, but I don't know better ripping application for Linux and I do think it should be available for all popular distros, especially Ubuntu latest LTS. Please consider creating a package for upcoming 16.04 (April). Thank you.

**Comment by centic9** [comment]
FYI, I usually build packages of soundkonverter in my PPAs for Ubuntu for the different versions at the following locations:

* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-trusty-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-vivid-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-wily-ppa
* https://launchpad.net/~dominik-stadler/+archive/ubuntu/dsta-xenial-ppa

2.2.0 is currently building and should be available in a few minutes.

Just ping me if I miss a release for some time so I can update the packages, the sources plus the Debian/Ubuntu packaging for the packages are at https://github.com/centic9/soundkonverter-ppa

**Comment by HessiJames** [comment]
Thank you, I updated the [docs](https://github.com/HessiJames/soundkonverter/wiki/Installing-soundKonverter#ubuntu).

**Comment by kokosowy** [comment]
This is fantastic! Thanks guys, that's what I was looking for! Much appreciated!

**Comment by kokosowy** [comment]
centic9, just one thing I noticed. I don't think you need to maintain separate PPAs for each Ubuntu version. You can merge everything to only one repository. Release versions will be still distinguished by packages.

**Comment by centic9** [comment]
Yes, I know, but I decided to set it up this way on-purpose as I don't much like PPAs with lots of packages in it. 

I have one that is on the version that I personally use and which includes additional things like current KDE and then one PPA for each Ubuuntu-release so that the list of packages in each is clean and I can keep older packages for older versions in their respective PPA without clobbering the current PPAs with too many outdated packages.

**Comment by kokosowy** [comment]
Ok, I thought it would be easier for system upgrade. Thanks anyway!
