### ISSUE TITLE
Ripped and encoded but directory is invisible, files disappeared!

### ISSUE THREAD

**Issue by cliffsloane555** [HessiJames/soundkonverter#43]
I have SK 2.1.2, running on Ubuntu 16.4.
A problem has just emerged that I had not seen before. I ripped a CD, encoded them to a dedicated directory, and the directory was not visible in File Manager.
I searched for the files, and they all came up in Search, but the directory could not be displayed.
I rebooted, and they all disappeared! No search could find them.

Is this a problem with my SK settings, or a larger Ubuntu issue?

Cliff

**Comment by HessiJames** [comment]
That sounds very strange and I can't imagine how that could happen. Have you tried opening one of these files from the search results? Have you double checked the file paths? Are you sure you didn't rip to a temporary directory? Because if there were files that couldn't be displayed, it sounds less of a soundkonverter problem. Maybe a file system error? What file system do you use? Have you tried fsck?
And of course, can you reproduce the bug?

**Comment by cliffsloane555** [comment]
Daniel, I figured it out.
The problem is that I was manually creating directories by writing it into
the path. In Monopolyland (Win), that would automatically trigger the
creation of that directory. I tried just clicking on "New Directory" each
step, and it shows up.

And now that I have upgraded to Ubuntu 16.04, rip speeds are far better.
Things are going swimmingly.

Cliff

**Comment by HessiJames** [comment]
I'm not sure what "writing it into the path" means, but still, glad it works now.
